// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuwyuhkr6qZ3F8g0vGYuAXYiPbEVoTT4',
    appId: '1:684491647397:web:45ccf2e32f3def40e6e04c',
    messagingSenderId: '684491647397',
    projectId: 'floracure',
    authDomain: 'floracure.firebaseapp.com',
    storageBucket: 'floracure.appspot.com',
    measurementId: 'G-T9ES2TGJTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfUvhyKUuIZRH1GL2RWhA62Ag7QMIfGPA',
    appId: '1:684491647397:android:3a8952f2596a582ae6e04c',
    messagingSenderId: '684491647397',
    projectId: 'floracure',
    storageBucket: 'floracure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTyflwLQFjA-yBEQJCI8Sv76TEz0oDd6M',
    appId: '1:684491647397:ios:5a8723fed619df8fe6e04c',
    messagingSenderId: '684491647397',
    projectId: 'floracure',
    storageBucket: 'floracure.appspot.com',
    iosBundleId: 'com.example.floraCure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTyflwLQFjA-yBEQJCI8Sv76TEz0oDd6M',
    appId: '1:684491647397:ios:293348cbb9aba649e6e04c',
    messagingSenderId: '684491647397',
    projectId: 'floracure',
    storageBucket: 'floracure.appspot.com',
    iosBundleId: 'com.example.floraCure.RunnerTests',
  );
}
